In [122]:
import pandas as pd
import numpy as np
import glob

path = './Sensor_Data/'
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

sensor_data = pd.concat(li, axis=0, ignore_index=True)

In [191]:
sensor_data_filter = sensor_data.filter(items=['animal_activity', "temp_without_drink_cycles", 'time', 'CowID'])
sensor_data_filter['time']=pd.to_datetime(sensor_data_filter['time'])
calv_feature = pd.read_excel("./Sensor_Data/Calving_Features.xlsx")
calv_feature = calv_feature.filter(items=['ID', "DAT_TIME_FCAL"])

In [192]:
sensor_data_filter = sensor_data_filter.set_index('time')
sensor_data_aggre = sensor_data_filter.groupby("CowID").resample('H').mean()
sensor_data_aggre = sensor_data_aggre.drop(['CowID'], axis=1)
sensor_data_aggre.reset_index(inplace=True) 
sensor_data_aggre.head()

   CowID                time  animal_activity  temp_without_drink_cycles
0     10 2018-12-04 16:00:00             3.72                      39.38
1     10 2018-12-04 17:00:00             3.40                      39.74
2     10 2018-12-04 18:00:00             2.42                      39.63
3     10 2018-12-04 19:00:00             1.42                      39.88
4     10 2018-12-04 20:00:00             1.54                      40.37

In [193]:
calv_feature['DAT_TIME_FCAL']=pd.to_datetime(calv_feature['DAT_TIME_FCAL'])
calv_feature = calv_feature.assign(Date=calv_feature.DAT_TIME_FCAL.dt.round('H'))
calv_feature.head()

      ID       DAT_TIME_FCAL                Date
0  11262 2018-09-04 13:30:00 2018-09-04 14:00:00
1  11313 2018-11-22 05:00:00 2018-11-22 05:00:00
2  11343 2018-11-03 01:20:00 2018-11-03 01:00:00
3  11390 2018-09-15 01:20:00 2018-09-15 01:00:00
4  11433 2018-07-12 11:00:00 2018-07-12 11:00:00

In [324]:
def merge_10_days_before_calving(original_data,calve_data,cowId):
    filtered_original_data = original_data[original_data["CowID"]==cowId]
    filtered_calve_data = calve_data[calve_data["CowID"]==cowId]
    result = pd.DataFrame(data = None, columns= filtered_original_data.columns)
    for index, row in filtered_calve_data.iterrows():
        tmp = filtered_original_data[(filtered_original_data.time >= row.time - pd.to_timedelta("20day")) & (filtered_original_data.time <= row.time)]
        result = result.append(tmp)
    return result

In [325]:
merge_data = sensor_data_aggre.merge(calv_feature, left_on=['CowID','time'], right_on=['ID','Date'],how='left')
merge_data['isCalving'] = pd.notna(merge_data['ID']).astype(int)
merge_data = merge_data.filter(items=['animal_activity', "temp_without_drink_cycles","CowID","isCalving","time"])
merge_data = merge_data.dropna()
calve_time = merge_data[merge_data['isCalving']==1]
merge_data_filter = pd.DataFrame(data = None, columns= merge_data.columns)
for cowId in calve_time["CowID"]:
    time_merge_df = merge_10_days_before_calving(merge_data,calve_time,cowId)
    merge_data_filter = merge_data_filter.append(time_merge_df)
merge_data_filter['CowID'] = merge_data_filter['CowID'].astype(float)
merge_data_filter['isCalving'] = merge_data_filter['isCalving'].astype(int)
merge_data_filter = merge_data_filter.drop_duplicates()
merge_data_filter.head()

,animal_activity,temp_without_drink_cycles,CowID,isCalving,time
96,2.54,40.04,10.00,0,2018-12-08 16:00:00
97,2.32,39.56,10.00,0,2018-12-08 17:00:00
98,1.06,39.77,10.00,0,2018-12-08 18:00:00
99,1.05,40.17,10.00,0,2018-12-08 19:00:00
100,2.12,40.37,10.00,0,2018-12-08 20:00:00

In [344]:
max(merge_data_filter['time'])

Timestamp('2019-10-02 08:00:00')

In [327]:
label = "isCalving"
test_labels = merge_data_filter[label].values

In [328]:
from azureml.automl.core.forecasting_parameters import ForecastingParameters

forecast_parameters = ForecastingParameters(time_column_name='time', 
                                            forecast_horizon=50,
                                            short_series_handling_configuration='auto',
                                            freq = 'H',
                                            target_lags='auto')

In [329]:
from azureml.core.workspace import Workspace
from azureml.core.experiment import Experiment
from azureml.train.automl import AutoMLConfig
import logging

automl_config = AutoMLConfig(task='forecasting',
                             primary_metric='normalized_root_mean_squared_error',
                             experiment_timeout_minutes=15,
                             enable_early_stopping=True,
                             training_data=merge_data_filter,
                             label_column_name=label,
                             n_cross_validations=2,
                            time_column_name='time',                                            
                             forecast_horizon=50,
                            short_series_handling_configuration='auto',
                            freq = 'H',
                            target_lags='auto',
                            time_series_id_column_names = 'CowID')
#                              enable_ensembling=False,
#                              **forecasting_parameters)

In [330]:
ws = Workspace.from_config()
experiment = Experiment(ws, "Tutorial-automl-forecasting")
local_run = experiment.submit(automl_config, show_output=True)
best_run, fitted_model = local_run.get_output()

Running on local machine
Parent Run ID: AutoML_d6301b53-e971-4543-85e3-c391125b6975

Current status: DatasetFeaturization. Beginning to featurize the dataset.
Current status: DatasetFeaturizationCompleted. Completed featurizing the dataset.
Heuristic parameters: Target_Lag = '[0]'.
Current status: DatasetCrossValidationSplit. Generating individually featurized CV splits.
Current status: DatasetFeaturization. Beginning to featurize the CV split.
Current status: DatasetFeaturizationCompleted. Completed featurizing the CV split.
Current status: DatasetFeaturization. Beginning to featurize the CV split.
Current status: DatasetFeaturizationCompleted. Completed featurizing the CV split.

****************************************************************************************************
DATA GUARDRAILS:

TYPE:         Frequency detection
STATUS:       PASSED
DESCRIPTION:  The time series was analyzed, all data points are aligned with detected frequency.


****************************************************************************************************

TYPE:         Missing feature values imputation
STATUS:       PASSED
DESCRIPTION:  No feature missing values were detected in the training data.
              Learn more about missing value imputation: https://aka.ms/AutomatedMLFeaturization

****************************************************************************************************

TYPE:         Memory Issues Detection
STATUS:       PASSED
DESCRIPTION:  The selected horizon and lag values were analyzed, and no potential memory issues were detected.
              Learn more about time-series forecasting configurations: https://aka.ms/AutomatedMLForecastingConfiguration

****************************************************************************************************

TYPE:         Short series handling
STATUS:       FIXED
DESCRIPTION:  Automated ML detected that some series did not contain enough data points to train a model. To continue with training, these short series have been dropped or padded.

DETAILS:      Each series must have enough data points to successfully train a model. To avoid failures on these short series, automated ML will drop these series, or pad them by adding data points to the beginning of each of the series. If a series is dropped for training then a model will not produce predictions for those series.
+---------------------------------+
|Number of series dropped         |
+=================================+
|19                               |
+---------------------------------+

****************************************************************************************************
Current status: ModelSelection. Beginning model selection.

****************************************************************************************************
ITERATION: The iteration being evaluated.
PIPELINE: A summary description of the pipeline being evaluated.
DURATION: Time taken for the current iteration.
METRIC: The result of computing score on the fitted pipeline.
BEST: The best observed score thus far.
****************************************************************************************************

 ITERATION   PIPELINE                                       DURATION      METRIC      BEST
         0   RobustScaler LassoLars                         0:00:50       0.5311    0.5311
         1   RobustScaler DecisionTree                      0:00:45       0.1876    0.1876
         2   StandardScalerWrapper DecisionTree             0:00:44       0.1876    0.1876
         3   RobustScaler DecisionTree                      0:00:43       0.1876    0.1876
         4   StandardScalerWrapper ElasticNet               0:00:44       0.5311    0.1876
         5   MinMaxScaler DecisionTree                      0:00:45       0.2241    0.1876
         6   MinMaxScaler ElasticNet                        0:00:38       0.5311    0.1876
         7   StandardScalerWrapper DecisionTree             0:00:35       0.1876    0.1876
         8   StandardScalerWrapper DecisionTree             0:00:38       0.2065    0.1876
         9   RobustScaler DecisionTree                      0:00:41       0.1876    0.1876
        10   RobustScaler ElasticNet                        0:00:37       0.5311    0.1876
        11   RobustScaler DecisionTree                      0:00:41       0.1876    0.1876
        12   RobustScaler DecisionTree                      0:00:39       0.1876    0.1876
        13   StandardScalerWrapper DecisionTree             0:00:43       0.1863    0.1863
        14   MinMaxScaler DecisionTree                      0:00:40       0.1876    0.1863
        15   VotingEnsemble                                 0:01:15       0.5311    0.1863
Stopping criteria reached at iteration 16. Ending experiment.
****************************************************************************************************
Current status: BestRunExplainModel. Best run model explanations started
Current status: ModelExplanationDataSetSetup. Model explanations data setup completed
Current status: PickSurrogateModel. Choosing LightGBM as the surrogate model for explanations
Current status: EngineeredFeatureExplanations. Computation of engineered features started
Current status: EngineeredFeatureExplanations. Computation of engineered features completed
Current status: RawFeaturesExplanations. Computation of raw features started
Current status: RawFeaturesExplanations. Computation of raw features completed
Current status: BestRunExplainModel. Best run model explanations completed
****************************************************************************************************

In [331]:
label_query = test_labels.copy().astype(np.float)
label_query.fill(np.nan)
label_fcst, data_trans = fitted_model.forecast(
    forecast_destination=pd.Timestamp(2020, 1, 1))

In [343]:
data_trans

                              animal_activity  temp_without_drink_cycles  \
time                CowID
2018-07-06 04:00:00 9659.00              4.58                      39.74
2018-07-06 05:00:00 9659.00              4.58                      39.74
2018-07-06 06:00:00 9659.00              4.58                      39.74
2018-07-06 07:00:00 9659.00              4.58                      39.74
2018-07-06 08:00:00 9659.00              4.58                      39.74
...                                       ...                        ...
2021-05-28 00:00:00 12478.00             4.58                      39.74
                    12479.00             4.58                      39.74
                    12481.00             4.58                      39.74
                    12482.00             4.58                      39.74
                    12495.00             4.58                      39.74

                              animal_activity_WASNULL  \
time                CowID
2018-07-06 04:00:00 9659.00                         1
2018-07-06 05:00:00 9659.00                         1
2018-07-06 06:00:00 9659.00                         1
2018-07-06 07:00:00 9659.00                         1
2018-07-06 08:00:00 9659.00                         1
...                                               ...
2021-05-28 00:00:00 12478.00                        1
                    12479.00                        1
                    12481.00                        1
                    12482.00                        1
                    12495.00                        1

                              temp_without_drink_cycles_WASNULL  grain_CowID  \
time                CowID
2018-07-06 04:00:00 9659.00                                   1          311
2018-07-06 05:00:00 9659.00                                   1          311
2018-07-06 06:00:00 9659.00                                   1          311
2018-07-06 07:00:00 9659.00                                   1          311
2018-07-06 08:00:00 9659.00                                   1          311
...                                                         ...          ...
2021-05-28 00:00:00 12478.00                                  1          816
                    12479.00                                  1          817
                    12481.00                                  1          818
                    12482.00                                  1          819
                    12495.00                                  1          820

                              _automl_year  _automl_half  _automl_quarter  \
time                CowID
2018-07-06 04:00:00 9659.00           2018             2                3
2018-07-06 05:00:00 9659.00           2018             2                3
2018-07-06 06:00:00 9659.00           2018             2                3
2018-07-06 07:00:00 9659.00           2018             2                3
2018-07-06 08:00:00 9659.00           2018             2                3
...                                    ...           ...              ...
2021-05-28 00:00:00 12478.00          2021             1                2
                    12479.00          2021             1                2
                    12481.00          2021             1                2
                    12482.00          2021             1                2
                    12495.00          2021             1                2

                              _automl_month  _automl_day  _automl_hour  \
time                CowID
2018-07-06 04:00:00 9659.00               7            6             4
2018-07-06 05:00:00 9659.00               7            6             5
2018-07-06 06:00:00 9659.00               7            6             6
2018-07-06 07:00:00 9659.00               7            6             7
2018-07-06 08:00:00 9659.00               7            6             8
...                                     ...          ...           ...
2021-05-28 00:00:00 12478.00              5           28             0
                    12479.00              5           28             0
                    12481.00              5           28             0
                    12482.00              5           28             0
                    12495.00              5           28             0

                              _automl_am_pm  _automl_hour12  _automl_wday  \
time                CowID
2018-07-06 04:00:00 9659.00               0               4             4
2018-07-06 05:00:00 9659.00               0               5             4
2018-07-06 06:00:00 9659.00               0               6             4
2018-07-06 07:00:00 9659.00               0               7             4
2018-07-06 08:00:00 9659.00               0               8             4
...                                     ...             ...           ...
2021-05-28 00:00:00 12478.00              0               0             4
                    12479.00              0               0             4
                    12481.00              0               0             4
                    12482.00              0               0             4
                    12495.00              0               0             4

                              _automl_qday  _automl_week  _automl_target_col
time                CowID
2018-07-06 04:00:00 9659.00              6            27                0.00
2018-07-06 05:00:00 9659.00              6            27                0.00
2018-07-06 06:00:00 9659.00              6            27                0.00
2018-07-06 07:00:00 9659.00              6            27                0.00
2018-07-06 08:00:00 9659.00              6            27                0.00
...                                    ...           ...                 ...
2021-05-28 00:00:00 12478.00            58            21                0.00
                    12479.00            58            21                0.00
                    12481.00            58            21                0.00
                    12482.00            58            21                0.00
                    12495.00            58            21                0.00

[16422091 rows x 17 columns]

### Azure Setup (Ignore now)

In [5]:
import os, glob, shutil

if not os.path.exists('./data'):
    os.mkdir('./data')
for f in glob.glob('./Sensor_Data/*.csv'):
    shutil.move(f, './data/')
print("Data moved!")

Data moved!

In [6]:
# acount metadata

AZURE_SUBSCRIPTION_ID = '32fda87f-7ad1-4d47-9078-eaa80469c690'
ML_WORKSPACE_NAME = 'dairyFarmDemo'
AZURE_IOT_HUB_NAME = 'dairyfarm5412'
RESOURCE_GROUP_NAME = 'cs5412-final-project'
LOCATION = 'East US 2'
STORAGE_ACCOUNT_NAME = 'dairydatastorage'
STORAGE_ACCOUNT_KEY = 'bLrvIMcD0g3P1LiCTYKnqSWWkEyeah7RWsfZdSRfz7U4DiWt/oHyPPL0XThvvy4WyTN0SUqdB9WTzTY9QTqiRw=='
STORAGE_ACCOUNT_CONTAINER = 'container5412'
# DATASTORE_NAME = 'dairydata'

In [9]:
import os, glob, shutil
from azureml.core import Workspace
workspace_name = ML_WORKSPACE_NAME
subscription_id = AZURE_SUBSCRIPTION_ID
resource_group = RESOURCE_GROUP_NAME
location = LOCATION

if not os.path.exists('./aml_config'):
    os.mkdir('./aml_config')
ws = Workspace.from_config()

Note, we have launched a browser for you to login. For old experience with device code, use "az login --use-device-code"

Performing interactive authentication. Please follow the instructions on the terminal.
You have logged in. Now let us find all the subscriptions to which you have access...
Interactive authentication successfully completed.

In [10]:
import azureml.core
import pandas as pd
from azureml.core import Workspace

output = {}
output['SDK version'] = azureml.core.VERSION
output['Subscription ID'] = ws.subscription_id
output['Workspace'] = ws.name
output['Resource Group'] = ws.resource_group
output['Location'] = ws.location
pd.set_option('display.max_colwidth', -1)
pd.DataFrame(data=output, index=['']).T

<ipython-input-10-8bd734a592f9>:13: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)

SDK version      1.27.0
Subscription ID  32fda87f-7ad1-4d47-9078-eaa80469c690
Workspace        dairyFarmDemo
Resource Group   cs5412-final-project
Location         eastus

In [11]:
from azureml.core import Datastore, Workspace, Datastore, Dataset

datastore_name = DATASTORE_NAME
datastore = Datastore.get(ws, datastore_name)
# label_datastore_path = (datastore,'/label_data_large.csv')
# label_dataset = Dataset.Tabular.from_delimited_files(path=label_datastore_path)

# record_datastore_path = (datastore,'/record_data_large.csv')
# record_dataset = Dataset.Tabular.from_delimited_files(path=record_datastore_path)

# print("Data retrieved!")

NameError: name 'DATASTORE_NAME' is not defined